### ISSUE TITLE
drain_filter

### ISSUE THREAD

**Issue by toyboot4e** [LPGhatguy/thunderdome#23]
[Vec::drain_filter](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain_filter) is an unstable Rust feature. Alternative to it in `Arena` would be helpful in some cases.

Links:

* [Tracking issue](https://github.com/rust-lang/rust/issues/43244) for `drain_filter`
* [library/alloc/src/vec/drain_filter.rs](https://github.com/rust-lang/rust/blob/master/library/alloc/src/vec/drain_filter.rs)

**Comment by LPGhatguy** [comment]
Because `Vec::drain_filter` is still unstable, I'm uncertain about adding it to `Arena`! I think I'd like to wait for the bikeshedding on the `Vec` version to settle down, since it seems like that API is still in flux.

In particular, it seems like it's uncertain what should happen to filtered elements!

**Comment by toyboot4e** [comment]
I see, thank you <3
